-- Core tenant + identity schema: pharmacies (tenants), user accounts, refresh tokens.
-- Every later migration that adds a tenant-scoped table follows the same
-- shape: a UUID primary key generated by the application, an audit trail
-- (created_at/updated_at/version), and a pharmacy_id foreign key.

create table pharmacies (
    id                              uuid primary key,
    created_at                      timestamptz not null,
    updated_at                      timestamptz not null,
    version                         bigint not null default 0,

    name                            varchar(255) not null,
    contact_email                   varchar(255) not null,
    contact_phone                   varchar(64),
    address_line                    varchar(255),
    city                            varchar(128),
    country                         varchar(128),
    tax_registration_number         varchar(128),
    currency_code                   varchar(3) not null default 'USD',
    timezone                        varchar(64) not null default 'UTC',
    plan                            varchar(32) not null default 'FREE_PILOT',
    subscription_status             varchar(32) not null default 'TRIALING',
    trial_ends_at                   timestamptz,
    low_stock_threshold_default     integer not null default 10,
    expiry_warning_days_default     integer not null default 90
);

create table user_accounts (
    id                  uuid primary key,
    created_at          timestamptz not null,
    updated_at          timestamptz not null,
    version             bigint not null default 0,

    pharmacy_id         uuid references pharmacies (id),
    email               varchar(255) not null,
    full_name           varchar(255) not null,
    phone_number        varchar(64),
    role                varchar(32) not null,
    auth_provider       varchar(32) not null,
    status              varchar(32) not null,
    google_subject_id   varchar(255),
    last_login_at       timestamptz,

    constraint uk_user_accounts_email unique (email),
    constraint uk_user_accounts_google_subject_id unique (google_subject_id)
);

create index idx_user_accounts_pharmacy_id on user_accounts (pharmacy_id);

create table refresh_tokens (
    id                      uuid primary key,
    created_at              timestamptz not null,
    updated_at              timestamptz not null,
    version                 bigint not null default 0,

    user_id                 uuid not null references user_accounts (id),
    token_hash              varchar(255) not null,
    device_label            varchar(255),
    expires_at              timestamptz not null,
    revoked                 boolean not null default false,
    revoked_at              timestamptz,
    rotated_to_token_id     uuid,

    constraint uk_refresh_tokens_token_hash unique (token_hash)
);

create index idx_refresh_tokens_user_id on refresh_tokens (user_id);
